// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrdwecfbbyirlktdpnfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyZHdlY2ZiYnlpcmxrdGRwbmZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NTYwNTksImV4cCI6MjA3MTMzMjA1OX0.C1HNNO7IeMffrr_sC4y_krATvi4ur1M6AuC8RVQ1VJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});